AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Tzero CICD Demo Test
Resources:
  TzeroLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      CodeUri: ./LambdaCode
      Description: 'Tzero Lambda function for CICD Demo'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::299869144443:role/LambdaRole_anushukla'
      Events:
        getAZsAPI:
          Type: Api
          Properties:
            Path: /getazs
            Method: get
      Environment:
        Variables:
          REGION: eu-west-1