AWSTemplateFormatVersion: 2010-09-09
Description: Lambda CD for CapStone Project
Resources:
  CrtPutLambda:
    Type: 'AWS::Lambda::Function'
    Properties:
      Code:
        S3Bucket: anushuk-lambda-pipeline
        S3Key: 969095604600482e213c2b361fda459c
      Description: Lambda function for CapStone Project Put request to DynamoDB
      Tags:
        - Value: SAM
          Key: 'lambda:createdBy'
      MemorySize: 128
      Environment:
        Variables:
          REGION: us-east-1
      Handler: lambda_function.lambda_handler
      Role: 'arn:aws:iam::862117308857:role/MyLambdaRole1'
      Timeout: 30
      Runtime: python3.6
  DynGetLambdaGetResourcePermissionProd:
    Type: 'AWS::Lambda::Permission'
    Properties:
      Action: 'lambda:invokeFunction'
      Principal: apigateway.amazonaws.com
      FunctionName: !Ref DynGetLambda
      SourceArn: !Sub
        - >-
          arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${__ApiId__}/${__Stage__}/GET/
        - __Stage__: Prod
          __ApiId__: !Ref ServerlessRestApi
  CrtPutLambdaPutResourcePermissionTest:
    Type: 'AWS::Lambda::Permission'
    Properties:
      Action: 'lambda:invokeFunction'
      Principal: apigateway.amazonaws.com
      FunctionName: !Ref CrtPutLambda
      SourceArn: !Sub
        - >-
          arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${__ApiId__}/${__Stage__}/PUT/
        - __Stage__: '*'
          __ApiId__: !Ref ServerlessRestApi
  ServerlessRestApiProdStage:
    Type: 'AWS::ApiGateway::Stage'
    Properties:
      DeploymentId: !Ref ServerlessRestApiDeploymentca1f4a6ee1
      RestApiId: !Ref ServerlessRestApi
      StageName: Prod
  ServerlessRestApiDeploymentca1f4a6ee1:
    Type: 'AWS::ApiGateway::Deployment'
    Properties:
      RestApiId: !Ref ServerlessRestApi
      Description: 'RestApi deployment id: ca1f4a6ee149a70caa70f59ced7d23911d567fe8'
      StageName: Stage
  DynGetLambda:
    Type: 'AWS::Lambda::Function'
    Properties:
      Code:
        S3Bucket: anushuk-lambda-pipeline
        S3Key: da0f626d955cf547606f12e0512fd8c5
      Description: Lambda function for CapStone Project Get request to DynamoDB
      Tags:
        - Value: SAM
          Key: 'lambda:createdBy'
      MemorySize: 128
      Environment:
        Variables:
          REGION: us-east-1
      Handler: lambda_function.lambda_handler
      Role: 'arn:aws:iam::862117308857:role/MyLambdaRole1'
      Timeout: 30
      Runtime: python3.6
  ServerlessRestApi:
    Type: 'AWS::ApiGateway::RestApi'
    Properties:
      Body:
        info:
          version: '1.0'
          title: !Ref 'AWS::StackName'
        paths:
          /:
            put:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri: !Sub >-
                  arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${CrtPutLambda.Arn}/invocations
              responses: {}
            get:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri: !Sub >-
                  arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${DynGetLambda.Arn}/invocations
              responses: {}
        swagger: '2.0'
  DynGetLambdaGetResourcePermissionTest:
    Type: 'AWS::Lambda::Permission'
    Properties:
      Action: 'lambda:invokeFunction'
      Principal: apigateway.amazonaws.com
      FunctionName: !Ref DynGetLambda
      SourceArn: !Sub
        - >-
          arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${__ApiId__}/${__Stage__}/GET/
        - __Stage__: '*'
          __ApiId__: !Ref ServerlessRestApi
  CrtPutLambdaPutResourcePermissionProd:
    Type: 'AWS::Lambda::Permission'
    Properties:
      Action: 'lambda:invokeFunction'
      Principal: apigateway.amazonaws.com
      FunctionName: !Ref CrtPutLambda
      SourceArn: !Sub
        - >-
          arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${__ApiId__}/${__Stage__}/PUT/
        - __Stage__: Prod
          __ApiId__: !Ref ServerlessRestApi
