AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Lambda CD for CapStone Project
Resources:
  CourseCatalog:
    Type: AWS::DynamoDB::Table
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: ./GetLambda
      AttributeDefinitions:
        - AttributeName: category
          AttributeType: S
        - AttributeName: course
          AttributeType: s
      KeySchema:
        - AttributeName: category
          KeyType: HASH
        - AttributeName: course
          KeyType: RANGE
      ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
  PutLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: ./PutLambdaCapStone
      Description: 'Lambda function for CapStone Project Put request to DynamoDB'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::862117308857:role/MyLambdaRole1'
      Events:
        PutResource:
          Type: Api
          Properties:
            Path: "/"
            Method: PUT
      Environment:
        Variables:
          REGION: us-east-1
          DB_TABLE_NAME: CourseCatalog
  GetLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: ./GetLambda
      Description: 'Lambda function for CapStone Project Get request to DynamoDB'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::862117308857:role/MyLambdaRole1'
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: "/"
            Method: GET
      Environment:
        Variables:
          REGION: us-east-1
          DB_TABLE_NAME: CourseCatalog